# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_of_transaction', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('phone_number', models.CharField(max_length=13)),
                ('transaction_type', models.CharField(choices=[('DP', 'DP'), ('WD', 'WD')], default='DP', max_length=2)),
            ],
        ),
    ]
