# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdrawl')], default='DP', max_length=2),
        ),
    ]
