# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_auto_20170404_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
