# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_auto_20170404_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_id',
            field=models.ForeignKey(on_delete=models.SET('No transactions.'), to='mpesa.Transaction'),
        ),
    ]
