# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0007_auto_20170404_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=20)),
                ('phone_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=7)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.ForeignKey(on_delete=models.SET('No transactions.'), to='mpesa.Customer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
