# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0008_auto_20170404_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
