# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-04 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0013_auto_20170404_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='add a description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
