# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-05 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0015_auto_20170405_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone_number',
            new_name='customer_name',
        ),
    ]
