# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-05 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0016_auto_20170405_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
