# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0017_customer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
    ]
